# TensorFlow Basics

In [1]:
import tensorflow as tf

/Users/sprod007/.conda/envs/tfl/envs/tfdeeplearning/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:458: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/sprod007/.conda/envs/tfl/envs/tfdeeplearning/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:459: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/sprod007/.conda/envs/tfl/envs/tfdeeplearning/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:460: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 

In [2]:
# Make sure you are using 1.3 for exact sytnax matching!
print(tf.__version__)

1.3.0


## Tensors

In [3]:
hello = tf.constant('Hello')

In [4]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [5]:
world = tf.constant('World')

In [6]:
result = hello + world

In [7]:
result

<tf.Tensor 'add:0' shape=() dtype=string>

In [8]:
type(result)

tensorflow.python.framework.ops.Tensor

In [9]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [10]:
result

b'HelloWorld'

** Computations **

In [11]:
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)

In [12]:
type(tensor_1)

tensorflow.python.framework.ops.Tensor

In [13]:
tensor_1 + tensor_2

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [14]:
sess

In [15]:
sess.close()

## Operations

In [16]:
const = tf.constant(10)

In [17]:
fill_mat = tf.fill((4,4),10)

In [18]:
myzeros = tf.zeros((4,4))

In [19]:
myones = tf.ones((4,4))

In [20]:
myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)

In [21]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [22]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

## Interactive Session

Useful for Notebook Sessions

In [23]:
# Only run this cell once!
sess = tf.InteractiveSession()

In [24]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.38059983 -0.83973163  0.23288411 -0.73105294]
 [ 0.16541591 -0.27176     0.52709     0.38728622]
 [-0.7684547   0.8317461   0.6041369  -1.2597617 ]
 [ 0.00294607  1.4961065  -0.17084871  0.0978367 ]]


[[0.98392785 0.10831726 0.04717529 0.34190345]
 [0.29556954 0.69115996 0.39743257 0.48854864]
 [0.86552525 0.27013898 0.12204552 0.5405319 ]
 [0.6311735  0.94875157 0.43962204 0.77089477]]




## Matrix Multiplication

In [25]:
a = tf.constant([ [1,2],
                  [3,4] ])

In [26]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [27]:
b = tf.constant([[10],[100]])

In [28]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [29]:
result = tf.matmul(a,b)

In [30]:
result.eval()

array([[210],
       [430]], dtype=int32)